### ISSUE TITLE
Heap out-of-bounds write in `sstring_HammingCorr`

### ISSUE THREAD

**Issue by jlebar** [umontreal-simul/TestU01-2009#3]
Steps to reproduce:

```
unsigned long rng() {
  return 0xbf2d4b4db3d8dfb1;
}

int main() {
  unif01_Gen* gen = unif01_CreateExternGenBitsL("foo", rng);
  sstring_Res* res = sstring_CreateRes();
  sstring_HammingCorr(gen, res, 1, 500000000, 0, 30, 30);  // boom
}
```

```
==3676465==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x624000008038 at pc 0x5623b62d2017 bp 0x7ffe3b384bb0 sp 0x7ffe3b384ba8
READ of size 8 at 0x624000008038 thread T0
    #0 0x5623b62d2016 in HammingCorr_L third_party/testu01/testu01_1_2_3/testu01/sstring.c:1652:7
    #1 0x5623b62d2016 in sstring_HammingCorr third_party/testu01/testu01_1_2_3/testu01/sstring.c:1747:3
    <snip>

0x624000008038 is located 56 bytes to the right of 7936-byte region [0x624000006100,0x624000008000)
allocated by thread T0 here:
    #0 0x5623b572e87d in malloc third_party/llvm/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x5623b62d3541 in util_Malloc third_party/testu01/testu01_1_2_3/mylib/util.c:78:8
    #2 0x5623b62d9c48 in tables_CreateMatrixL third_party/testu01/testu01_1_2_3/mylib/tables.c:81:21
    #3 0x5623b62d2355 in InitRes third_party/testu01/testu01_1_2_3/testu01/sstring.c:220:20
    #4 0x5623b62d1301 in sstring_HammingCorr third_party/testu01/testu01_1_2_3/testu01/sstring.c:1738:4
    <snip>

SUMMARY: AddressSanitizer: heap-buffer-overflow third_party/testu01/testu01_1_2_3/testu01/sstring.c:1652:7 in HammingCorr_L
Shadow bytes around the buggy address:
  0x0c487fff8fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c487fff8fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c487fff8fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c487fff8fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c487fff8ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c487fff9000: fa fa fa fa fa fa fa[fa]fa fa fa fa fa fa fa fa
  0x0c487fff9010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c487fff9020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c487fff9030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c487fff9040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c487fff9050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
```

asan says this is an out-of-bounds read, but the operation is `array[x]++`, so it's actually an OOB write.

I spent a while staring at the code to see if I couldn't figure out how to fix this, but I am pretty lost.

**Comment by jlebar** [comment]
HammingIndep also has an OOB write.

```
READ of size 8 at 0x6110000288c8 thread T0
    #0 0x7f0d53e533ab in HammingIndep_L third_party/testu01/testu01_1_2_3/testu01/sstring.c:1827:5
    #1 0x7f0d53e5093e in sstring_HammingIndep third_party/testu01/testu01_1_2_3/testu01/sstring.c:2049:3

0x6110000288c8 is located 8 bytes to the right of 256-byte region [0x6110000287c0,0x6110000288c0)
allocated by thread T0 here:
    #0 0x55c1a8dafb5d in malloc third_party/llvm/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x7f0d53d7c121 in util_Malloc third_party/testu01/testu01_1_2_3/mylib/util.c:65:8
    #2 0x7f0d53d79d1c in tables_CreateMatrixL third_party/testu01/testu01_1_2_3/mylib/tables.c:67:19
    #3 0x7f0d53e4f6bf in InitRes third_party/testu01/testu01_1_2_3/testu01/sstring.c:207:20
    #4 0x7f0d53e50424 in sstring_HammingIndep third_party/testu01/testu01_1_2_3/testu01/sstring.c:2019:4

SUMMARY: AddressSanitizer: heap-buffer-overflow third_party/testu01/testu01_1_2_3/testu01/sstring.c:1827:5 in HammingIndep_L
Shadow bytes around the buggy address:
  0x0c227fffd0c0: 00 00 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
  0x0c227fffd0d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c227fffd0e0: 00 00 00 00 00 00 00 00 00 fa fa fa fa fa fa fa
  0x0c227fffd0f0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c227fffd100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c227fffd110: 00 00 00 00 00 00 00 00 fa[fa]fa fa fa fa fa fa
  0x0c227fffd120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c227fffd130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c227fffd140: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c227fffd150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c227fffd160: 00 00 00 00 00 00 00 fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
```

**Comment by jlebar** [comment]
Dupe of https://github.com/umontreal-simul/TestU01-2009/issues/5#issuecomment-728371051
